server:
  port: 8089
spring:
  application:
    name: Microgram
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
  datasource:
    url: jdbc:h2:./db/Microgram;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:/db/changelog/master.yaml

logging:
  level:
    root: info
  file:
    path: logs
avatar:
  upload:
    dir: data/
